=== DEFRA/data-returns-data-exchange/schemas/landfill_gas_monitoring.xsd
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" 
           xmlns:lgm="http://ea.gov.uk/DR/LGM" 
           attributeFormDefault="unqualified"
           elementFormDefault="qualified">

    <!-- Type definitions in separate files -->
    <xs:include schemaLocation="includes/StringTypes.xsd" />
    <xs:include schemaLocation="includes/MeasurePeriodList.xsd" />
    <xs:include schemaLocation="includes/Dates.xsd" />
    <xs:include schemaLocation="includes/ReturnType.xsd" />
    <xs:include schemaLocation="includes/UnitType.xsd" />
    <xs:include schemaLocation="includes/TestMethodType.xsd" />
    <xs:include schemaLocation="includes/ParameterType.xsd" />
    <xs:include schemaLocation="includes/CiCType.xsd" />

    <xs:element name="returns">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="return" maxOccurs="unbounded" minOccurs="0">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element type="LFG_Required_String" name="eaID"/>
                            <xs:element type="LFG_mandatoryStringMax30" name="siteName"/>
                            <xs:element type="LFG_returnType" name="retType"/>
                            <xs:element type="LFG_DateTime" name="dateSt"/>
                            <xs:element type="LFG_optionalValidDateTime" name="dateEn"/>
                            <xs:element type="LFG_periodNameType" name="periodName"/> 
                            <xs:element type="LFG_FourDigitYear" name="periodYear"/>
                            <xs:element type="LFG_OptionalStringMax255" name="sampleRef"/>
                            <xs:element type="LFG_OptionalStringMax255" name="sampledBy"/>
                            <xs:element type="LFG_mandatoryStringMax255" name="monPoint"/>
                            <xs:element type="LFG_parameterType" name="parameter"/>
                            <xs:element type="LFG_mandatoryValueTypeMax30" name="value"/>
                            <xs:element type="LFG_Optional_String" name="tValue"/>
                            <xs:element type="LFG_unitType" name="Unit"/>
                            <xs:element type="LFG_measurePeriodType" name="MeasurePeriod"/>
                            <xs:element type="LFG_testMethodType" name="testMethod"/>
                            <xs:element type="LFG_OptionalStringMax255" name="Comments"/>
                            <xs:element type="LFG_CiCType" name="CiC"/>
                            <xs:element type="LFG_OptionalStringMax255" name="addParameter1"/>
                            <xs:element type="LFG_OptionalStringMax255" name="addParameter2"/>
                            <xs:element type="LFG_OptionalStringMax255" name="addParameter3"/>
                            <xs:element type="LFG_OptionalStringMax255" name="addParameter4"/>
                            <xs:element type="LFG_OptionalStringMax255" name="addParameter5"/>
                        </xs:sequence>
                        <xs:attribute type="xs:integer" name="srcId" use="optional"/>
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
</xs:schema>

=== DEFRA/data-returns-data-exchange/external_resources/schema/permit-returns-test-xml-file.xml
<?xml version="1.0" encoding="utf-8"?>
<returns xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:noNamespaceSchemaLocation="landfill_gas_monitoring.xsd">

         <!-- Exported from cvs convertion in back end code -->

    <return srcId="2">
        <eaID xmlId="4">AB3002SQ</eaID>
        <siteName xmlId="5">ABC Limited</siteName>
        <retType xmlId="6">Landfill Gas Monitoring</retType>
        <dateSt xmlId="7">2015-08-05</dateSt>
        <dateEn xmlId="8">2015-08-05</dateEn>
        <periodName xmlId="9">Period 1</periodName>
        <periodYear xmlId="10">1970</periodYear>
        <sampleRef xmlId="11">Sample Ref</sampleRef>
        <sampledBy xmlId="12">Sampled by 1</sampledBy>
        <monPoint xmlId="13">Monitor point 1</monPoint>
        <parameter xmlId="14">Temperature</parameter>
        <value xmlId="15">100</value>
        <tValue xmlId="16">Test Text</tValue>
        <Unit xmlId="17">Metres</Unit>
        <MeasurePeriod xmlId="18">Annual</MeasurePeriod>
        <testMethod xmlId="19">Test method 1</testMethod>
        <Comments xmlId="20">Test CSV file with no errors</Comments>
        <CiC xmlId="21">True</CiC>
        <addParameter1 xmlId="22">Par 1</addParameter1>
        <addParameter2 xmlId="23">Par 2</addParameter2>
        <addParameter3 xmlId="24">Par 3</addParameter3>
        <addParameter4 xmlId="25">Par 4</addParameter4>
        <addParameter5 xmlId="26">Par 5</addParameter5>
    </return>
    <return srcId="3">
        <eaID xmlId="29">AB3002SQ</eaID>
        <siteName xmlId="30">ABC Limited</siteName>
        <retType xmlId="31">Landfill Gas Monitoring</retType>
        <dateSt xmlId="32">2015-08-05</dateSt>
        <dateEn xmlId="33">2015-08-05</dateEn>
        <periodName xmlId="34">Period 1</periodName>
        <periodYear xmlId="35">1970</periodYear>
        <sampleRef xmlId="36">Sample Ref</sampleRef>
        <sampledBy xmlId="37">Sampled by 1</sampledBy>
        <monPoint xmlId="38">Monitor point 1</monPoint>
        <parameter xmlId="39">Temperature</parameter>
        <value xmlId="40">100</value>
        <tValue xmlId="41">Test Text</tValue>
        <Unit xmlId="42">Metres</Unit>
        <MeasurePeriod xmlId="43">Annual</MeasurePeriod>
        <testMethod xmlId="44">Test method 1</testMethod>
        <Comments xmlId="45">Test CSV file with no errors</Comments>
        <CiC xmlId="46">True</CiC>
        <addParameter1 xmlId="47">Par 1</addParameter1>
        <addParameter2 xmlId="48">Par 2</addParameter2>
        <addParameter3 xmlId="49">Par 3</addParameter3>
        <addParameter4 xmlId="50">Par 4</addParameter4>
        <addParameter5 xmlId="51">Par 5</addParameter5>
    </return>
    <return srcId="4">
        <eaID xmlId="54">AB3002SQ</eaID>
        <siteName xmlId="55">ABC Limited</siteName>
        <retType xmlId="56">Landfill Gas Monitoring</retType>
        <dateSt xmlId="57">2015-08-05</dateSt>
        <dateEn xmlId="58">2015-08-05</dateEn>
        <periodName xmlId="59">Period 1</periodName>
        <periodYear xmlId="60">1970</periodYear>
        <sampleRef xmlId="61">Sample Ref</sampleRef>
        <sampledBy xmlId="62">Sampled by 1</sampledBy>
        <monPoint xmlId="63">Monitor point 1</monPoint>
        <parameter xmlId="64">Temperature</parameter>
        <value xmlId="65">100</value>
        <tValue xmlId="66">Test Text</tValue>
        <Unit xmlId="67">Metres</Unit>
        <MeasurePeriod xmlId="68">Annual</MeasurePeriod>
        <testMethod xmlId="69">Test method 1</testMethod>
        <Comments xmlId="70">Test CSV file with no errors</Comments>
        <CiC xmlId="71">True</CiC>
        <addParameter1 xmlId="72">Par 1</addParameter1>
        <addParameter2 xmlId="73">Par 2</addParameter2>
        <addParameter3 xmlId="74">Par 3</addParameter3>
        <addParameter4 xmlId="75">Par 4</addParameter4>
        <addParameter5 xmlId="76">Par 5</addParameter5>
    </return>
    <return srcId="5">
        <eaID xmlId="79">AB3002SQ</eaID>
        <siteName xmlId="80">ABC Limited</siteName>
        <retType xmlId="81">Landfill Gas Monitoring</retType>
        <dateSt xmlId="82">2015-08-05</dateSt>
        <dateEn xmlId="83">2015-08-05</dateEn>
        <periodName xmlId="84">Period 1</periodName>
        <periodYear xmlId="85">1970</periodYear>
        <sampleRef xmlId="86">Sample Ref</sampleRef>
        <sampledBy xmlId="87">Sampled by 1</sampledBy>
        <monPoint xmlId="88">Monitor point 1</monPoint>
        <parameter xmlId="89">Temperature</parameter>
        <value xmlId="90">100</value>
        <tValue xmlId="91">Test Text</tValue>
        <Unit xmlId="92">Metres</Unit>
        <MeasurePeriod xmlId="93">Annual</MeasurePeriod>
        <testMethod xmlId="94">Test method 1</testMethod>
        <Comments xmlId="95">Test CSV file with no errors</Comments>
        <CiC xmlId="96">True</CiC>
        <addParameter1 xmlId="97">Par 1</addParameter1>
        <addParameter2 xmlId="98">Par 2</addParameter2>
        <addParameter3 xmlId="99">Par 3</addParameter3>
        <addParameter4 xmlId="100">Par 4</addParameter4>
        <addParameter5 xmlId="101">Par 5</addParameter5>
    </return>
    <return srcId="6">
        <eaID xmlId="104">AB3002SQ</eaID>
        <siteName xmlId="105">ABC Limited</siteName>
        <retType xmlId="106">Landfill Gas Monitoring</retType>
        <dateSt xmlId="107">2015-08-05</dateSt>
        <dateEn xmlId="108">2015-08-05</dateEn>
        <periodName xmlId="109">Period 1</periodName>
        <periodYear xmlId="110">1970</periodYear>
        <sampleRef xmlId="111">Sample Ref</sampleRef>
        <sampledBy xmlId="112">Sampled by 1</sampledBy>
        <monPoint xmlId="113">Monitor point 1</monPoint>
        <parameter xmlId="114">Temperature</parameter>
        <value xmlId="115">100</value>
        <tValue xmlId="116">Test Text</tValue>
        <Unit xmlId="117">Metres</Unit>
        <MeasurePeriod xmlId="118">Annual</MeasurePeriod>
        <testMethod xmlId="119">Test method 1</testMethod>
        <Comments xmlId="120">Test CSV file with no errors</Comments>
        <CiC xmlId="121">True</CiC>
        <addParameter1 xmlId="122">Par 1</addParameter1>
        <addParameter2 xmlId="123">Par 2</addParameter2>
        <addParameter3 xmlId="124">Par 3</addParameter3>
        <addParameter4 xmlId="125">Par 4</addParameter4>
        <addParameter5 xmlId="126">Par 5</addParameter5>
    </return>
</returns>
